#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-directory-server
Version  : 2.0.0.m21
Release  : 8
URL      : https://github.com/apache/directory-server/archive/2.0.0-M21.tar.gz
Source0  : https://github.com/apache/directory-server/archive/2.0.0-M21.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M2/apacheds-jdbm-parent-2.0.0-M2.pom
Source2  : https://repo1.maven.org/maven2/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M3/apacheds-jdbm-parent-2.0.0-M3.pom
Source3  : https://repo1.maven.org/maven2/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.jar
Source4  : https://repo1.maven.org/maven2/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.pom
Source5  : https://repo1.maven.org/maven2/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3/apacheds-jdbm1-2.0.0-M3.jar
Source6  : https://repo1.maven.org/maven2/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3/apacheds-jdbm1-2.0.0-M3.pom
Source7  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.jar
Source8  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.pom
Source9  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-api/2.0.0-M15/apacheds-core-api-2.0.0-M15.jar
Source10  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-api/2.0.0-M15/apacheds-core-api-2.0.0-M15.pom
Source11  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.jar
Source12  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.pom
Source13  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-avl/2.0.0-M15/apacheds-core-avl-2.0.0-M15.jar
Source14  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-avl/2.0.0-M15/apacheds-core-avl-2.0.0-M15.pom
Source15  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.jar
Source16  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.pom
Source17  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-constants/2.0.0-M15/apacheds-core-constants-2.0.0-M15.jar
Source18  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-constants/2.0.0-M15/apacheds-core-constants-2.0.0-M15.pom
Source19  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.jar
Source20  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.pom
Source21  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.jar
Source22  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.pom
Source23  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.jar
Source24  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.pom
Source25  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-shared/2.0.0-M15/apacheds-core-shared-2.0.0-M15.jar
Source26  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-shared/2.0.0-M15/apacheds-core-shared-2.0.0-M15.pom
Source27  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.jar
Source28  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.pom
Source29  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core/2.0.0-M15/apacheds-core-2.0.0-M15.jar
Source30  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core/2.0.0-M15/apacheds-core-2.0.0-M15.pom
Source31  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.jar
Source32  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.pom
Source33  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar
Source34  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.pom
Source35  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.jar
Source36  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.pom
Source37  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15/apacheds-interceptor-kerberos-2.0.0-M15.jar
Source38  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15/apacheds-interceptor-kerberos-2.0.0-M15.pom
Source39  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.jar
Source40  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.pom
Source41  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15/apacheds-interceptors-admin-2.0.0-M15.jar
Source42  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15/apacheds-interceptors-admin-2.0.0-M15.pom
Source43  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.jar
Source44  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.pom
Source45  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15/apacheds-interceptors-authn-2.0.0-M15.jar
Source46  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15/apacheds-interceptors-authn-2.0.0-M15.pom
Source47  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.jar
Source48  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.pom
Source49  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15/apacheds-interceptors-authz-2.0.0-M15.jar
Source50  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15/apacheds-interceptors-authz-2.0.0-M15.pom
Source51  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.jar
Source52  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.pom
Source53  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15/apacheds-interceptors-changelog-2.0.0-M15.jar
Source54  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15/apacheds-interceptors-changelog-2.0.0-M15.pom
Source55  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.jar
Source56  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.pom
Source57  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15/apacheds-interceptors-collective-2.0.0-M15.jar
Source58  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15/apacheds-interceptors-collective-2.0.0-M15.pom
Source59  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.jar
Source60  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.pom
Source61  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15/apacheds-interceptors-event-2.0.0-M15.jar
Source62  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15/apacheds-interceptors-event-2.0.0-M15.pom
Source63  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.jar
Source64  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.pom
Source65  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15/apacheds-interceptors-exception-2.0.0-M15.jar
Source66  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15/apacheds-interceptors-exception-2.0.0-M15.pom
Source67  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.jar
Source68  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.pom
Source69  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.jar
Source70  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.pom
Source71  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15/apacheds-interceptors-journal-2.0.0-M15.jar
Source72  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15/apacheds-interceptors-journal-2.0.0-M15.pom
Source73  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.jar
Source74  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.pom
Source75  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15/apacheds-interceptors-normalization-2.0.0-M15.jar
Source76  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15/apacheds-interceptors-normalization-2.0.0-M15.pom
Source77  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.jar
Source78  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.pom
Source79  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.jar
Source80  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.pom
Source81  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15/apacheds-interceptors-operational-2.0.0-M15.jar
Source82  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15/apacheds-interceptors-operational-2.0.0-M15.pom
Source83  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.jar
Source84  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.pom
Source85  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15/apacheds-interceptors-referral-2.0.0-M15.jar
Source86  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15/apacheds-interceptors-referral-2.0.0-M15.pom
Source87  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.jar
Source88  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.pom
Source89  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15/apacheds-interceptors-schema-2.0.0-M15.jar
Source90  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15/apacheds-interceptors-schema-2.0.0-M15.pom
Source91  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.jar
Source92  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.pom
Source93  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15/apacheds-interceptors-subtree-2.0.0-M15.jar
Source94  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15/apacheds-interceptors-subtree-2.0.0-M15.pom
Source95  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.jar
Source96  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.pom
Source97  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15/apacheds-interceptors-trigger-2.0.0-M15.jar
Source98  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15/apacheds-interceptors-trigger-2.0.0-M15.pom
Source99  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.jar
Source100  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.pom
Source101  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors/2.0.0-M15/apacheds-interceptors-2.0.0-M15.pom
Source102  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors/2.0.0-M21/apacheds-interceptors-2.0.0-M21.pom
Source103  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15/apacheds-jdbm-partition-2.0.0-M15.jar
Source104  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15/apacheds-jdbm-partition-2.0.0-M15.pom
Source105  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.jar
Source106  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.pom
Source107  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar
Source108  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.pom
Source109  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.jar
Source110  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.pom
Source111  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15/apacheds-ldif-partition-2.0.0-M15.jar
Source112  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15/apacheds-ldif-partition-2.0.0-M15.pom
Source113  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.jar
Source114  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.pom
Source115  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15/apacheds-mavibot-partition-2.0.0-M15.jar
Source116  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15/apacheds-mavibot-partition-2.0.0-M15.pom
Source117  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.jar
Source118  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.pom
Source119  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-parent/2.0.0-M15/apacheds-parent-2.0.0-M15.pom
Source120  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-parent/2.0.0-M21/apacheds-parent-2.0.0-M21.pom
Source121  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15/apacheds-protocol-kerberos-2.0.0-M15.jar
Source122  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15/apacheds-protocol-kerberos-2.0.0-M15.pom
Source123  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.jar
Source124  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.pom
Source125  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15/apacheds-protocol-ldap-2.0.0-M15.jar
Source126  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15/apacheds-protocol-ldap-2.0.0-M15.pom
Source127  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.jar
Source128  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.pom
Source129  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15/apacheds-protocol-shared-2.0.0-M15.jar
Source130  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15/apacheds-protocol-shared-2.0.0-M15.pom
Source131  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.jar
Source132  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.pom
Source133  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.jar
Source134  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.pom
Source135  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.jar
Source136  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.pom
Source137  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.jar
Source138  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.pom
Source139  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.jar
Source140  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.pom
Source141  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15/apacheds-xdbm-partition-2.0.0-M15.jar
Source142  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15/apacheds-xdbm-partition-2.0.0-M15.pom
Source143  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.jar
Source144  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.pom
Summary  : ApacheDS
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-directory-server-data = %{version}-%{release}
Requires: mvn-directory-server-license = %{version}-%{release}

%description
ApacheDS ${version}

%package data
Summary: data components for the mvn-directory-server package.
Group: Data

%description data
data components for the mvn-directory-server package.


%package license
Summary: license components for the mvn-directory-server package.
Group: Default

%description license
license components for the mvn-directory-server package.


%prep
%setup -q -n directory-server-2.0.0-M21

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-directory-server
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-directory-server/NOTICE
cp installers-maven-plugin/src/main/resources/org/apache/directory/server/installers/LICENSE %{buildroot}/usr/share/package-licenses/mvn-directory-server/installers-maven-plugin_src_main_resources_org_apache_directory_server_installers_LICENSE
cp installers-maven-plugin/src/main/resources/org/apache/directory/server/installers/NOTICE %{buildroot}/usr/share/package-licenses/mvn-directory-server/installers-maven-plugin_src_main_resources_org_apache_directory_server_installers_NOTICE
cp installers-maven-plugin/src/main/resources/org/apache/directory/server/installers/macosxpkg/License.rtf %{buildroot}/usr/share/package-licenses/mvn-directory-server/installers-maven-plugin_src_main_resources_org_apache_directory_server_installers_macosxpkg_License.rtf
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M2/apacheds-jdbm-parent-2.0.0-M2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M3/apacheds-jdbm-parent-2.0.0-M3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3/apacheds-jdbm1-2.0.0-M3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3/apacheds-jdbm1-2.0.0-M3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M15
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M15/apacheds-core-api-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M15
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M15/apacheds-core-api-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M15
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M15/apacheds-core-avl-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M15
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M15/apacheds-core-avl-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M15
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M15/apacheds-core-constants-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M15
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M15/apacheds-core-constants-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M15
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M15/apacheds-core-shared-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M15
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M15/apacheds-core-shared-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M15
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M15/apacheds-core-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M15
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M15/apacheds-core-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15/apacheds-interceptor-kerberos-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15/apacheds-interceptor-kerberos-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15/apacheds-interceptors-admin-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15/apacheds-interceptors-admin-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15/apacheds-interceptors-authn-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15/apacheds-interceptors-authn-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15/apacheds-interceptors-authz-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15/apacheds-interceptors-authz-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15/apacheds-interceptors-changelog-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15/apacheds-interceptors-changelog-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15/apacheds-interceptors-collective-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15/apacheds-interceptors-collective-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15/apacheds-interceptors-event-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15/apacheds-interceptors-event-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15/apacheds-interceptors-exception-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15/apacheds-interceptors-exception-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15/apacheds-interceptors-journal-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15/apacheds-interceptors-journal-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15/apacheds-interceptors-normalization-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15
cp %{SOURCE76} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15/apacheds-interceptors-normalization-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21
cp %{SOURCE77} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21
cp %{SOURCE78} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21
cp %{SOURCE79} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21
cp %{SOURCE80} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15
cp %{SOURCE81} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15/apacheds-interceptors-operational-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15
cp %{SOURCE82} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15/apacheds-interceptors-operational-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21
cp %{SOURCE83} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21
cp %{SOURCE84} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15
cp %{SOURCE85} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15/apacheds-interceptors-referral-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15
cp %{SOURCE86} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15/apacheds-interceptors-referral-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21
cp %{SOURCE87} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21
cp %{SOURCE88} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15
cp %{SOURCE89} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15/apacheds-interceptors-schema-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15
cp %{SOURCE90} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15/apacheds-interceptors-schema-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21
cp %{SOURCE91} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21
cp %{SOURCE92} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15
cp %{SOURCE93} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15/apacheds-interceptors-subtree-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15
cp %{SOURCE94} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15/apacheds-interceptors-subtree-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21
cp %{SOURCE95} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21
cp %{SOURCE96} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15
cp %{SOURCE97} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15/apacheds-interceptors-trigger-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15
cp %{SOURCE98} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15/apacheds-interceptors-trigger-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21
cp %{SOURCE99} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21
cp %{SOURCE100} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M15
cp %{SOURCE101} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M15/apacheds-interceptors-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M21
cp %{SOURCE102} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M21/apacheds-interceptors-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15
cp %{SOURCE103} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15/apacheds-jdbm-partition-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15
cp %{SOURCE104} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15/apacheds-jdbm-partition-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21
cp %{SOURCE105} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21
cp %{SOURCE106} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15
cp %{SOURCE107} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15
cp %{SOURCE108} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21
cp %{SOURCE109} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21
cp %{SOURCE110} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15
cp %{SOURCE111} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15/apacheds-ldif-partition-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15
cp %{SOURCE112} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15/apacheds-ldif-partition-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21
cp %{SOURCE113} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21
cp %{SOURCE114} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15
cp %{SOURCE115} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15/apacheds-mavibot-partition-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15
cp %{SOURCE116} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15/apacheds-mavibot-partition-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21
cp %{SOURCE117} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21
cp %{SOURCE118} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M15
cp %{SOURCE119} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M15/apacheds-parent-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M21
cp %{SOURCE120} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M21/apacheds-parent-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15
cp %{SOURCE121} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15/apacheds-protocol-kerberos-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15
cp %{SOURCE122} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15/apacheds-protocol-kerberos-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21
cp %{SOURCE123} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21
cp %{SOURCE124} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15
cp %{SOURCE125} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15/apacheds-protocol-ldap-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15
cp %{SOURCE126} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15/apacheds-protocol-ldap-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21
cp %{SOURCE127} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21
cp %{SOURCE128} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15
cp %{SOURCE129} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15/apacheds-protocol-shared-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15
cp %{SOURCE130} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15/apacheds-protocol-shared-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21
cp %{SOURCE131} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21
cp %{SOURCE132} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21
cp %{SOURCE133} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21
cp %{SOURCE134} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21
cp %{SOURCE135} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21
cp %{SOURCE136} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21
cp %{SOURCE137} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21
cp %{SOURCE138} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21
cp %{SOURCE139} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21
cp %{SOURCE140} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15
cp %{SOURCE141} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15/apacheds-xdbm-partition-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15
cp %{SOURCE142} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15/apacheds-xdbm-partition-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21
cp %{SOURCE143} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21
cp %{SOURCE144} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M2/apacheds-jdbm-parent-2.0.0-M2.pom
/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm-parent/2.0.0-M3/apacheds-jdbm-parent-2.0.0-M3.pom
/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.jar
/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.pom
/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3/apacheds-jdbm1-2.0.0-M3.jar
/usr/share/java/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M3/apacheds-jdbm1-2.0.0-M3.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M15/apacheds-core-api-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M15/apacheds-core-api-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M15/apacheds-core-avl-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M15/apacheds-core-avl-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M15/apacheds-core-constants-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M15/apacheds-core-constants-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M15/apacheds-core-shared-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M15/apacheds-core-shared-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M15/apacheds-core-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M15/apacheds-core-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15/apacheds-interceptor-kerberos-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M15/apacheds-interceptor-kerberos-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15/apacheds-interceptors-admin-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M15/apacheds-interceptors-admin-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15/apacheds-interceptors-authn-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M15/apacheds-interceptors-authn-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15/apacheds-interceptors-authz-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M15/apacheds-interceptors-authz-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15/apacheds-interceptors-changelog-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M15/apacheds-interceptors-changelog-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15/apacheds-interceptors-collective-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M15/apacheds-interceptors-collective-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15/apacheds-interceptors-event-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M15/apacheds-interceptors-event-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15/apacheds-interceptors-exception-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M15/apacheds-interceptors-exception-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15/apacheds-interceptors-journal-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M15/apacheds-interceptors-journal-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15/apacheds-interceptors-normalization-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M15/apacheds-interceptors-normalization-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15/apacheds-interceptors-operational-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M15/apacheds-interceptors-operational-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15/apacheds-interceptors-referral-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M15/apacheds-interceptors-referral-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15/apacheds-interceptors-schema-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M15/apacheds-interceptors-schema-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15/apacheds-interceptors-subtree-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M15/apacheds-interceptors-subtree-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15/apacheds-interceptors-trigger-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M15/apacheds-interceptors-trigger-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M15/apacheds-interceptors-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M21/apacheds-interceptors-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15/apacheds-jdbm-partition-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M15/apacheds-jdbm-partition-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15/apacheds-ldif-partition-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M15/apacheds-ldif-partition-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15/apacheds-mavibot-partition-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M15/apacheds-mavibot-partition-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M15/apacheds-parent-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M21/apacheds-parent-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15/apacheds-protocol-kerberos-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M15/apacheds-protocol-kerberos-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15/apacheds-protocol-ldap-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M15/apacheds-protocol-ldap-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15/apacheds-protocol-shared-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M15/apacheds-protocol-shared-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15/apacheds-xdbm-partition-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M15/apacheds-xdbm-partition-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-directory-server/NOTICE
/usr/share/package-licenses/mvn-directory-server/installers-maven-plugin_src_main_resources_org_apache_directory_server_installers_LICENSE
/usr/share/package-licenses/mvn-directory-server/installers-maven-plugin_src_main_resources_org_apache_directory_server_installers_NOTICE
/usr/share/package-licenses/mvn-directory-server/installers-maven-plugin_src_main_resources_org_apache_directory_server_installers_macosxpkg_License.rtf
