#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-directory-server
Version  : 2.0.0.m21
Release  : 1
URL      : https://github.com/apache/directory-server/archive/2.0.0-M21.tar.gz
Source0  : https://github.com/apache/directory-server/archive/2.0.0-M21.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.jar
Source2  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.pom
Source3  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.jar
Source4  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.pom
Source5  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.jar
Source6  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.pom
Source7  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.jar
Source8  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.pom
Source9  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.jar
Source10  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.pom
Source11  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.jar
Source12  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.pom
Source13  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.jar
Source14  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.pom
Source15  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.jar
Source16  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.pom
Source17  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar
Source18  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.pom
Source19  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.jar
Source20  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.pom
Source21  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.jar
Source22  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.pom
Source23  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.jar
Source24  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.pom
Source25  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.jar
Source26  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.pom
Source27  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.jar
Source28  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.pom
Source29  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.jar
Source30  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.pom
Source31  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.jar
Source32  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.pom
Source33  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.jar
Source34  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.pom
Source35  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.jar
Source36  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.pom
Source37  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.jar
Source38  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.pom
Source39  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.jar
Source40  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.pom
Source41  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.jar
Source42  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.pom
Source43  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.jar
Source44  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.pom
Source45  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.jar
Source46  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.pom
Source47  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.jar
Source48  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.pom
Source49  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.jar
Source50  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.pom
Source51  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.jar
Source52  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.pom
Source53  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.jar
Source54  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.pom
Source55  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-interceptors/2.0.0-M21/apacheds-interceptors-2.0.0-M21.pom
Source56  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.jar
Source57  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.pom
Source58  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar
Source59  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.pom
Source60  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.jar
Source61  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.pom
Source62  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.jar
Source63  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.pom
Source64  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.jar
Source65  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.pom
Source66  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-parent/2.0.0-M15/apacheds-parent-2.0.0-M15.pom
Source67  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-parent/2.0.0-M21/apacheds-parent-2.0.0-M21.pom
Source68  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.jar
Source69  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.pom
Source70  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.jar
Source71  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.pom
Source72  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.jar
Source73  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.pom
Source74  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.jar
Source75  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.pom
Source76  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.jar
Source77  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.pom
Source78  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.jar
Source79  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.pom
Source80  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.jar
Source81  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.pom
Source82  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.jar
Source83  : https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.pom
Summary  : ApacheDS
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-directory-server-data = %{version}-%{release}

%description
ApacheDS ${version}

%package data
Summary: data components for the mvn-directory-server package.
Group: Data

%description data
data components for the mvn-directory-server package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M21
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M21/apacheds-interceptors-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M15
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M15/apacheds-parent-2.0.0-M15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M21
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M21/apacheds-parent-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21
cp %{SOURCE76} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21
cp %{SOURCE77} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21
cp %{SOURCE78} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21
cp %{SOURCE79} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21
cp %{SOURCE80} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21
cp %{SOURCE81} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21
cp %{SOURCE82} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21
cp %{SOURCE83} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M21/apacheds-core-annotations-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M21/apacheds-core-api-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M21/apacheds-core-avl-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M21/apacheds-core-constants-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-integ/2.0.0-M21/apacheds-core-integ-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-jndi/2.0.0-M21/apacheds-core-jndi-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M21/apacheds-core-shared-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M21/apacheds-core-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M21/apacheds-i18n-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M21/apacheds-interceptor-kerberos-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M21/apacheds-interceptors-admin-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M21/apacheds-interceptors-authn-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M21/apacheds-interceptors-authz-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M21/apacheds-interceptors-changelog-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M21/apacheds-interceptors-collective-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M21/apacheds-interceptors-event-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M21/apacheds-interceptors-exception-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-hash/2.0.0-M21/apacheds-interceptors-hash-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M21/apacheds-interceptors-journal-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M21/apacheds-interceptors-normalization-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M21/apacheds-interceptors-number-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M21/apacheds-interceptors-operational-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M21/apacheds-interceptors-referral-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M21/apacheds-interceptors-schema-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M21/apacheds-interceptors-subtree-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M21/apacheds-interceptors-trigger-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-interceptors/2.0.0-M21/apacheds-interceptors-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M21/apacheds-jdbm-partition-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M21/apacheds-kerberos-codec-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M21/apacheds-ldif-partition-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M21/apacheds-mavibot-partition-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M15/apacheds-parent-2.0.0-M15.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-parent/2.0.0-M21/apacheds-parent-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M21/apacheds-protocol-kerberos-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M21/apacheds-protocol-ldap-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M21/apacheds-protocol-shared-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-annotations/2.0.0-M21/apacheds-server-annotations-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-config/2.0.0-M21/apacheds-server-config-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-server-integ/2.0.0-M21/apacheds-server-integ-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-test-framework/2.0.0-M21/apacheds-test-framework-2.0.0-M21.pom
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.jar
/usr/share/java/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M21/apacheds-xdbm-partition-2.0.0-M21.pom
